<tr>
	<td align="center">
        <div>
            <input type="checkbox" class="checkedrow" name="field[<?php echo $this->id?>]" title="Отметить"/>
        </div>
    </td>
	<td align="center">
        <div>
            <a title="Редактировать" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'edit', 'id' => $this->id), 'default', true);?>">
                <img width="16" height="16" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/editimg.png" />
            </a>
        </div>
    </td>
    
    
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            
            <?php $opt = new Admin_Model_AdminExampleModel();?>
            <?php $opt = $opt->getArticle($this->sect_id);?>
            
            <?php if (!empty($opt)) { ?>
                <?php echo $opt['title']; ?>
            <?php } else { ?>
                <span style="color:#FF9999">Не выбрано</span>
            <?php } ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php $opt = new Admin_Model_AdminExampleModel();?>
            <?php $opt = $opt->getArticle($this->cat_id);?>
            
            <?php if (!empty($opt)) { ?>
                <?php echo $opt['title']; ?>
            <?php } else { ?>
                <span style="color:#FF9999">Не выбрано</span>
            <?php } ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->datetime ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->title ?>
        </div>
    </td>
    <td>
        <?php $colName = "stxt";?>
        <div onmouseover="javascript: $('#popup_<?php echo $colName;?>_<?php echo $this->id;?>').show();" style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo Mc_Functions::substr($this->$colName, 100); ?>
        </div>
        <div class="table_popup_text" id="popup_<?php echo $colName;?>_<?php echo $this->id;?>" onmouseout="javascript:$(this).hide();">
            <?php echo $this->$colName ?>
        </div>
    </td>
    <td style="padding:5px 0px 0px 0px">
        <div style="overflow:hidden; text-align:left; width:60px;">
            <?php if (is_file(Admin_Model_AdminExampleModel::getPathUpload() . '/images/adm_'.$this->img)) { ?>
                <a class="highslide" onclick="return hs.expand(this)" href="<?php echo Admin_Model_AdminExampleModel::getUrlUpload() . '/images/s_' . $this->img; ?>">
                    <img style="width:50px; margin: 0px 0px 0px 5px" src="<?php echo Admin_Model_AdminExampleModel::getUrlUpload() . '/images/adm_'.$this->img; ?>" />
                </a>
            <?php } else { ?>
                <a class="highslide" onclick="return hs.expand(this)" href="<?php echo Zend_Registry::get('config')->url->upload . '/default_photo_250x250.jpg';?>">
                    <img style="width:50px; margin: 0px 0px 0px 5px" src="<?php echo Zend_Registry::get('config')->url->upload . '/default_photo_100x100.jpg';?>" />
                </a>
            <?php } ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:80px; max-width:400px">
            <?php if ('show' == $this->show) { ?>
                <span style="color:#339933">Да</span>
            <?php } elseif ('hide' == $this->show) { ?>
                <span style="color:#FF3333">Нет</span>
            <?php } elseif ('mod' == $this->show) { ?>
                <span style="color:#333399">На модерации</span>
            <?php } elseif ('del' == $this->show) { ?>
                <span style="color:gray">Удалено</span>
            <?php } else { ?>
                <span style="color:gray">Не указано</span>
            <?php } ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->order ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php
            $title = "Категории";
            $colName = "sect_id";
            $actionName = "filter-by-sect-id";
            $controllerName = "admin-example";
            $model = new Admin_Model_AdminExampleModel();
            
            $articles = $model->getArticles(array(
                "where" => "`{$colName}`='{$this->id}'",
            ));
                
            $count = '0';
            if(null !== $articles) {
                $count = count($articles);
            }
            
            if ($count > 0) {
                $count = "<span style='color:#55aa55'>{$count}</span>";
            } else {
                $count = "<span style='color:#aa5555'>{$count}</span>";
            }
            ?>
            
            <a href="<?php echo $this->url(array("controller" => $controllerName, "action" => $actionName, "value" => $this->id), $this->routeName); ?>">
                <?php echo $title; ?> (<?php echo $count;?>)
            </a>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php
            $title = "Товары";
            $colName = "cat_id";
            $actionName = "filter-by-cat-id";
            $controllerName = "admin-example";
            $model = new Admin_Model_AdminExampleModel();
            
            $articles = $model->getArticles(array(
                "where" => "`{$colName}`='{$this->id}'",
            ));
                
            $count = '0';
            if(null !== $articles) {
                $count = count($articles);
            }
            
            if ($count > 0) {
                $count = "<span style='color:#55aa55'>{$count}</span>";
            } else {
                $count = "<span style='color:#aa5555'>{$count}</span>";
            }
            ?>
            
            <a href="<?php echo $this->url(array("controller" => $controllerName, "action" => $actionName, "value" => $this->id), $this->routeName); ?>">
                <?php echo $title; ?> (<?php echo $count;?>)
            </a>
        </div>
    </td>
    
    
	<td align="center">
        <div>
            <a title="Удалить" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'delete', 'id' => $this->id), 'default', true);?>" onclick="return confirm('Вы действительно хотите удалить эту запись?')">
                <img width="18" height="18" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/delbut.png" />
            </a>
        </div>
    </td>
</tr>