<tr>
	<td align="center">
        <div>
            <input type="checkbox" class="checkedrow" name="field[<?php echo $this->id?>]" title="Отметить"/>
        </div>
    </td>
	<td align="center">
        <div>
            <a title="Редактировать" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'edit', 'id' => $this->id), 'default', true);?>">
                <img width="16" height="16" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/editimg.png" />
            </a>
        </div>
    </td>
    
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->banner($this->id); ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php $opt = new Admin_Model_BannersCategoriesModel();?>
            <?php $opt = $opt->getArticle($this->cat_id);?>
            
            <?php if (!empty($opt)) { ?>
                <?php echo $opt['title']; ?>
            <?php } else { ?>
                <span style="color:#FF9999">Не выбрано</span>
            <?php } ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->order ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:80px; max-width:400px">
            <?php if ('show' == $this->show) { ?>
                <span style="color:#339933">Да</span>
            <?php } elseif ('hide' == $this->show) { ?>
                <span style="color:#FF3333">Нет</span>
            <?php } elseif ('mod' == $this->show) { ?>
                <span style="color:#333399">На модерации</span>
            <?php } elseif ('del' == $this->show) { ?>
                <span style="color:gray">Удалено</span>
            <?php } else { ?>
                <span style="color:gray">Не указано</span>
            <?php } ?>
        </div>
    </td>
    
	<td align="center">
        <div>
            <a title="Удалить" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'delete', 'id' => $this->id), 'default', true);?>" onclick="return confirm('Вы действительно хотите удалить эту запись?')">
                <img width="18" height="18" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/delbut.png" />
            </a>
        </div>
    </td>
</tr>