<tr>
	<td align="center">
        <div>
            <input type="checkbox" class="checkedrow" name="field[<?php echo $this->id?>]" title="Отметить"/>
        </div>
    </td>
	<td align="center">
        <div>
            <a title="Редактировать" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'edit', 'id' => $this->id), 'default', true);?>">
                <img width="16" height="16" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/editimg.png" />
            </a>
        </div>
    </td>
    
    
    <td>
        <?php if ('menu' == $this->type) { ?>
            <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
                <?php
                $title = $this->title;
                $colName = "par_id";
                $actionName = "filter-by-par-id";
                $controllerName = "admin-resources";
                $model = new Admin_Model_AdminResourcesModel();

                $articles = $model->getArticles(array(
                    "where" => "`{$colName}`='{$this->id}'",
                ));

                $count = '0';
                if(null !== $articles) {
                    $count = count($articles);
                }

                if ($count > 0) {
                    $count = "<span style='color:#55aa55'>{$count}</span>";
                } else {
                    $count = "<span style='color:#aa5555'>{$count}</span>";
                }
                ?>

                <a href="<?php echo $this->url(array("controller" => $controllerName, "action" => $actionName, "value" => $this->id), $this->routeName); ?>">
                    <?php echo $title; ?> (<?php echo $count;?>)
                </a>
            </div>
        <?php } elseif('resource' == $this->type) { ?>
            <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
                <?php echo $this->title ?>
            </div>
        <?php } ?>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->name ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->order ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:80px; max-width:400px">
            <?php if ('show' == $this->show_in_menu) { ?>
                <span style="color:#339933">Да</span>
            <?php } elseif ('hide' == $this->show_in_menu) { ?>
                <span style="color:#FF3333">Нет</span>
            <?php } else { ?>
                <span style="color:gray">Не указано</span>
            <?php } ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:80px; max-width:400px">
            <?php if ('show' == $this->show_in_permissions) { ?>
                <span style="color:#339933">Да</span>
            <?php } elseif ('hide' == $this->show_in_permissions) { ?>
                <span style="color:#FF3333">Нет</span>
            <?php } else { ?>
                <span style="color:gray">Не указано</span>
            <?php } ?>
        </div>
    </td>
    
    
	<td align="center">
        <div>
            <a title="Удалить" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'delete', 'id' => $this->id), 'default', true);?>" onclick="return confirm('Вы действительно хотите удалить эту запись?')">
                <img width="18" height="18" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/delbut.png" />
            </a>
        </div>
    </td>
</tr>