<tr>
	<td align="center">
        <div>
            <input type="checkbox" class="checkedrow" name="field[<?php echo $this->id?>]" title="Отметить"/>
        </div>
    </td>
	<td align="center">
        <div>
            <a title="Редактировать" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'edit', 'id' => $this->id), 'default', true);?>">
                <img width="16" height="16" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/editimg.png" />
            </a>
        </div>
    </td>
    
    
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php $opt = new Admin_Model_CartOrdersModel();?>
            <?php $opt = $opt->getArticle($this->order_id);?>
            
            <?php if (!empty($opt)) { ?>
                <?php echo $opt['datetime']; ?>
                <?php $colName = 'progress';?>
                <?php if ('new' == $opt[$colName]) { ?>
                    <span style="color:#FF3333">новый</span>
                <?php } elseif ('in_progress' == $opt[$colName]) { ?>
                    <span style="color:#333399">в процессе...</span>
                <?php } elseif ('done' == $opt[$colName]) { ?>
                    <span style="color:#339933">выполнен</span>
                <?php } else { ?>
                    <span style="color:gray">Не указано</span>
                <?php } ?>
            <?php } else { ?>
                <span style="color:#FF9999">Не выбрано</span>
            <?php } ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php $opt = new Admin_Model_CatalogProductsModel();?>
            <?php $opt = $opt->getArticle($this->prod_id);?>
            
            <?php if (!empty($opt)) { ?>
                <?php echo $opt['title']; ?>
            <?php } else { ?>
                <span style="color:#FF9999">Не выбрано</span>
            <?php } ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->count;?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->price;?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->summ;?>
        </div>
    </td>
    
    
    <td align="center">
        <div>
            <a title="Удалить" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'delete', 'id' => $this->id), 'default', true);?>" onclick="return confirm('Вы действительно хотите удалить эту запись?')">
                <img width="18" height="18" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/delbut.png" />
            </a>
        </div>
    </td>
</tr>