<tr>
	<td align="center">
        <div>
            <input type="checkbox" class="checkedrow" name="field[<?php echo $this->id?>]" title="Отметить"/>
        </div>
    </td>
	<td align="center">
        <div>
            <a title="Редактировать" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'edit', 'id' => $this->id), 'default', true);?>">
                <img width="16" height="16" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/editimg.png" />
            </a>
        </div>
    </td>
    
    
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->title ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->meta_title ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->meta_description ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->meta_keywords ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; width:20px;">
            <?php echo $this->id ?>
        </div>
    </td>
    
    
	<td align="center">
        <div>
            <a title="Удалить" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'delete', 'id' => $this->id), 'default', true);?>" onclick="return confirm('Вы действительно хотите удалить эту запись?')">
                <img width="18" height="18" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/delbut.png" />
            </a>
        </div>
    </td>
</tr>