<tr>
	<td align="center">
        <div>
            <input type="checkbox" class="checkedrow" name="field[<?php echo $this->id?>]" title="<?php echo $this->translate('Отметить'); ?>"/>
        </div>
    </td>
	<td align="center">
        <div>
            <a title="<?php echo $this->translate('Редактировать'); ?>" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'edit', 'id' => $this->id), 'default', true);?>">
                <img width="16" height="16" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/editimg.png" />
            </a>
        </div>
    </td>
    
    
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->datetime ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->title ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->stxt ?>
        </div>
    </td>
    <td style="padding:5px 0px 0px 0px">
        <div style="overflow:hidden; text-align:left; width:60px;">
            <?php if (is_file(Admin_Model_ArticlesModel::getPathUpload() . '/images/adm_'.$this->img)) { ?>
                <a class="highslide" onclick="return hs.expand(this)" href="<?php echo Admin_Model_ArticlesModel::getUrlUpload() . '/images/s_' . $this->img; ?>">
                    <img style="width:50px; margin: 0px 0px 0px 5px" src="<?php echo Admin_Model_ArticlesModel::getUrlUpload() . '/images/adm_'.$this->img; ?>" />
                </a>
            <?php } else { ?>
                <a class="highslide" onclick="return hs.expand(this)" href="<?php echo Zend_Registry::get('config')->url->upload . '/default_photo_250x250.jpg';?>">
                    <img style="width:50px; margin: 0px 0px 0px 5px" src="<?php echo Zend_Registry::get('config')->url->upload . '/default_photo_100x100.jpg';?>" />
                </a>
            <?php } ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:80px; max-width:400px">
            <?php if ('show' == $this->show) { ?>
                <span style="color:#339933"><?php echo $this->translate('Да'); ?></span>
            <?php } elseif ('hide' == $this->show) { ?>
                <span style="color:#FF3333"><?php echo $this->translate('Нет'); ?></span>
            <?php } elseif ('mod' == $this->show) { ?>
                <span style="color:#333399"><?php echo $this->translate('На модерации'); ?></span>
            <?php } elseif ('del' == $this->show) { ?>
                <span style="color:gray"><?php echo $this->translate('Удалено'); ?></span>
            <?php } else { ?>
                <span style="color:gray"><?php echo $this->translate('Не указано'); ?></span>
            <?php } ?>
        </div>
    </td>
    <td class="seo">
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->url ?>
        </div>
    </td>
    <td class="seo">
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->meta_title ?>
        </div>
    </td>
    <td class="seo">
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo Mc_Functions::substr($this->meta_description, 200); ?>
        </div>
    </td>
    <td class="seo">
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo Mc_Functions::substr($this->meta_keywords, 200); ?>
        </div>
    </td>
    
    
	<td align="center">
        <div>
            <a title="<?php echo $this->translate('Удалить'); ?>" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'delete', 'id' => $this->id), 'default', true);?>" onclick="return confirm('<?php echo $this->translate('Вы действительно хотите удалить эту запись?'); ?>')">
                <img width="18" height="18" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/delbut.png" />
            </a>
        </div>
    </td>
</tr>