<tr>
	<td align="center">
        <div>
            <input type="checkbox" class="checkedrow" name="field[<?php echo $this->id?>]" title="Отметить"/>
        </div>
    </td>
	<td align="center">
        <div>
            <a title="Редактировать" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'edit', 'id' => $this->id, 'admin' => 'yes'), 'default', true);?>">
                <img width="16" height="16" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/editimg.png" />
            </a>
        </div>
    </td>
    
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:40px;">
            <?php echo $this->id ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->url ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->title ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo Mc_Functions::substr($this->txt, 75); ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php if (!empty($this->file)) { ?>
                <a href="<?php echo Zend_Registry::get('view')->urlUpload . '/files/' . $this->file;?>">
                    <?php echo $this->title ?>
                </a>
            <?php } else { ?>
                <span style="color:gray">Не указано</span>
            <?php }?>
        </div>
    </td>
    <td style="padding:5px 0px 0px 0px">
        <div style="overflow:hidden; text-align:left; width:60px;">
            <?php if (is_file(Zend_Registry::get('view')->pathUpload . '/images/adm_'.$this->img)) { ?>
                <a class="highslide" onclick="return hs.expand(this)" href="<?php echo Zend_Registry::get('view')->urlUpload . '/images/s_' . $this->img; ?>">
                    <img style="width:50px; margin: 0px 0px 0px 5px" src="<?php echo Zend_Registry::get('view')->urlUpload . '/images/adm_'.$this->img; ?>" />
                </a>
            <?php } else { ?>
                <a class="highslide" onclick="return hs.expand(this)" href="<?php echo Zend_Registry::get('config')->url->upload . '/default_photo_250x250.jpg';?>">
                    <img style="width:50px; margin: 0px 0px 0px 5px" src="<?php echo Zend_Registry::get('config')->url->upload . '/default_photo_100x100.jpg';?>" />
                </a>
            <?php } ?>
        </div>
    </td>
    
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->meta_title ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->meta_description ?>
        </div>
    </td>
    <td>
        <div style="overflow:hidden; margin-left:10px; text-align:left; min-width:120px;">
            <?php echo $this->meta_keywords ?>
        </div>
    </td>
    
    
    
	<td align="center">
        <div>
            <a title="Удалить" href="<?php echo $this->url(array('module' => Zend_Registry::get('view')->moduleName, 'controller' => Zend_Registry::get('view')->controllerName, 'action' => 'delete', 'id' => $this->id, 'admin' => 'yes'), 'default', true);?>" onclick="return confirm('Вы действительно хотите удалить эту запись?')">
                <img width="18" height="18" alt="" src="<?php echo Zend_Registry::get('config')->url->admin_content;?>/images/delbut.png" />
            </a>
        </div>
    </td>
</tr>